### PR TITLE
Update new project instructions

### PR DESCRIPTION
**Pull request by gapple**

### CODE REVIEW

**Comment by chknim** [comment]
Hey Justin,

How r u?  Hope all is well.

Could you lease help remove me from this project?

Chakrit

**Comment by timfernihough** [comment]
Chakrit, I'll take care of it. :)

**Comment by chknim** [comment]
Thank you Tim!

**Comment by timfernihough** [comment]
Actually @chknim , I can see that you aren't part of the collaborators list (this was removed on your last day at Myplanet).  You are still listed as a "Watcher" on the repo.  That doesn't get removed when I remove you from the organization, and I cannot control which repositories you watch.  This is a public repo, so you'll need to click "unwatch" at the top right of the repository page.

**Comment by chknim** [comment]
Oh... Gotcha.  Thank you Tim.  Sorry for misunderstanding.

**Pull request merged**
